config/routes.rb
FirehoseApp::Application.routes.draw do

   root 'static_pages#index'
   resources :pics

end

app/models/pic.rb
class Pic < ActiveRecord::Base

mount_uploader :image, ImageUploader 

validates :lesson, :presence => true, :numericality => { :less_than_or_equal_to => 100}

validates :emotion, :presence => true
validates :learned, :presence => true
validates :image, :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController

	def update
		@pic = Pic.find(params[:id])
		@pic.update_attributes( pic_params )
		
		if @pic.valid?
			redirect_to pics_path 
		else
			render :edit, :status => :unprocessable_entity
		end
	end

	def edit
		@pic = Pic.find(params[:id])
	end

	def destroy
		Pic.destroy(params[:id])
		redirect_to pics_path
	end


	def show
		@pic = Pic.find(params[:id])
	end

	def new
		@pic = Pic.new
	end

	def create
		@pic = Pic.create( pic_params )
		
		if @pic.valid?
			redirect_to pics_path 
		else
			render :new, :status => :unprocessable_entity
		end
	end


	def index
		@pics = Pic.all
	end

	private 

	def pic_params
		params.require(:pic).permit(:lesson, :emotion, :learned, :image)

	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def index
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirehoseApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <div class="nav-collapse collapse">
		<%= link_to 'Home', root_path, :class => 'brand' %>
		<ul class="nav">
			<li>
				<%= link_to 'My App', pics_path %>
			</li>
			<li>
				<%= link_to 'Input Page', new_pic_path %>
			</li>
		</ul>
      </div>
 
    </div>
  </div>
</div>
<%= yield %>

</body>
</html>

app/views/pics/_form.html.erb
	<%= simple_form_for @pic do  |f| %>
		<%= f.input :lesson, label: 'Enter your Lesson Number', placeholder: 'Lesson Number'%>
		<%= f.input :image, label: 'Upload Image Here', placeholder: 'Browse to select file'%>
		<%= f.input :emotion, label: 'What was your emotion', placeholder: 'example, stoked, happy, AHHHHH!!'%>
		<%= f.input :learned, label: 'And what did you leave', placeholder: 'Give as much details as possible'%>

		<%= submit_tag 'Submit', :class => 'btn btn-success btn-large' %>
	<% end %>

app/views/pics/edit.html.erb
<div class="stolen-frosty span6 offset3 text-center">

	<h1 class="stolen-h1">
		Please Update the form
	</h1>
	<%= render :partial => 'form' %>
</div>

app/views/pics/index.html.erb
	<% @pics.each do |pic|    %>
		<div class="stolen-frosty span4 text-center">

			<h1 class="stolen-h1">
				Lesson: <%= pic.lesson %>
				<br/>
			</h1>

			<h2>
				<%= link_to pic_path(pic) do %>
					<%= image_tag pic.image %>
				<% end %>
				<br/>
				Emmotion: <%= pic.emotion %>
				<br/>
				<br/>
				Learned: <%= pic.learned %>
				<br/>
			</h2>
		</div>
	<% end %>

app/views/pics/new.html.erb
<div class="stolen-frosty span4 text-center offset5">

	<h1 class="stolen-h1">
		Please Update the form
	</h1>
	<%= simple_form_for @pic do  |f| %>
		<%= f.input :lesson, label: 'Enter your Lesson Number', placeholder: 'Lesson Number'%>
		<%= f.input :image, label: 'Upload Image Here', placeholder: 'Browse to select file'%>
		<%= f.input :emotion, label: 'What was your emotion', placeholder: 'example, stoked, happy, AHHHHH!!'%>
		<%= f.input :learned, label: 'And what did you leave', placeholder: 'Give as much details as possible'%>

		<%= submit_tag 'Submit', :class => 'btn btn-success btn-large' %>
	<% end %>
</div>

app/views/pics/show.html.erb
<div class="stolen-frosty span6 offset1 text-center">
	<h1 class="stolen-h1">
		Lesson: <%= @pic.lesson %> 
	</br>
	</h1>
	<h2>
		I Felt: <%= @pic.emotion %>
		</br>
		And I learned: <%= @pic.learned %>
	</h2>
	<%= image_tag @pic.image %>
		</br>
	<%= link_to 'Back', pics_path, :class => 'btn btn-warning btn-large'    %>
	<%= link_to 'Delete', pic_path(@pic), :method => :delete, :class => 'btn btn-danger btn-large', :confirm => "Are you Sure?" %>
	<%= link_to 'Edit', edit_pic_path(@pic), :class => 'btn btn-warning btn-large' %>

</div>

app/views/static_pages/index.html.erb
<div class = "stolen-frosty span4 offset3 text-center">

	<h1 class="stolen-h1">Hi I'm Steve</h1>

	</br>

	<h2>
		I'm having a ton of learning web development 
	</h2>
	</br>


	<%= link_to 'Launch', pics_path, :class => 'btn btn-warning btn-large'    %>

</div>